version: '3.9'

services:
  client:
    image: ghcr.io/defelo/docker-ovpn:latest
    build: .
    restart: always
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./vpn.ovpn:/vpn.ovpn:ro
      - ./vpn.auth:/vpn.auth:ro
